title: Andrei Akimov
logo: /assets/DSCF4004-Edit.jpg
description: Expert with skills in Data Analytics, Data Visualisation, SQL, Python
show_downloads: false
theme: jekyll-theme-minimal

# remote_theme: pages-themes/minimal@v0.2.0
# plugins:
#  - jekyll-remote-theme

# Подключаем кастомные стили
#include:
#  - assets/mainpage_style.css
